/*
USER
USER_ID : VARCHAR2(100)
----------------------------

USER_PW : VARCHAR2(100)
USER_NAME : VARCHAR2(200)
USER_ADDRESS : VARCHAR2(300)
USER_EMAIL : VARCHAR2(300)
USER_PHONE : VARCHAR2(100)
*/

CREATE TABLE "USER"( -- 기존의 USER가 있기때문에""를 붙여 사용이 가능하다
	USER_ID VARCHAR2(100), -- PRIMARY KEY를 추가해도 된다,
	USER_PW VARCHAR2(100),
	USER_NAME VARCHAR2(200),
	USER_ADDRESS VARCHAR2(300),
	USER_EMAIL VARCHAR2(300),-- NOT NULL, -- UNIQUE NOT NULL을 추가해도 된다,
	USER_PHONE VARCHAR2(100),-- NOT NULL, -- UNIQUE NOT NULL을 추가해도 된다,
	CONSTRAINT USER_PK PRIMARY KEY(USER_ID),
	CONSTRAINT USER_UK1 UNIQUE(USER_EMAIL),
	CONSTRAINT USER_UK2 UNIQUE(USER_PHONE)
);
	-- ALTER TABLE [테이블명] MODIFY [컬럼명] NOT NULL
	ALTER TABLE "USER" MODIFY USER_EMAIL VARCHAR2(300) NOT NULL;
	ALTER TABLE "USER" MODIFY USER_PHONE VARCHAR2(100) NOT NULL;

-- 테이블 생성 후 unique key 추가
-- ALTER TABLE USER CONSTRAINT USER_UK3 UNIQUE NOT NULL(USER_ADDRESS)




/*
PRODUCT
PRODUCT_NUM : NUMBER
----------------------------

PRODUCT_NAME : VARCHAR(300)
PRODUCT_PRICE : NUMBER
PRODUCT_COUNT : NUMBER
*/

CREATE TABLE PRODUCT(
	PRODUCT_NUM NUMBER,
	PRODUCT_NAME VARCHAR2(300),
	PRODUCT_PRICE NUMBER,
	PRODUCT_COUNT NUMBER,
	CONSTRAINT PDT_PK PRIMARY KEY(PRODUCT_NUM)
);

DROP TABLE PORDUCT; -- 테이블 삭제

/*
ORDER ( 주문 )
ORDER_NUM : NUMBER
---------------------------

ORDER_DATE : DATE
USER_ID : VARCHAR2(100)
PRODUCT_NUM : NUMBER
*/

CREATE TABLE "ORDER"(
	ORDER_NUM NUMBER,
	ORDER_DATE DATE,
	USER_ID VARCHAR2(100), -- 외래키로 참조할 기중 컬럼의 데이터 타입과 길이를 반드시 맞춰야합니다
	PRODUCT_NUM NUMBER,
	CONSTRAINT ORDER_PK PRIMARY KEY(ORDER_NUM),
	-- CONSTRAINT 제약조건이름 제약조건종류(외래키로만들 컬럼) REFERENCES 기준이 될 테이플(기준이될 컬럼)
	CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES "USER"(USER_ID), -- REFERENCES(참조)
	CONSTRAINT PRODUCT_FK FOREIGN KEY(PRODUCT_NUM) REFERENCES PRODUCT(PRODUCT_NUM) 
);
/*
FLOWER
FLOWER_NAME VARCHAR2(200),
COLOR VARCHAR2(100),
PRICE NUMBER 
*/
CREATE TABLE FLOWER(
	FLOWER_NAME VARCHAR2(200),
	FLOWER_COLOR VARCHAR2(100),
	FLOWER_PRICE NUMBER,
	CONSTRAINT FLOWER_PK PRIMARY KEY(FLOWER_NAME)
);
/*
POT
POT_ID VARCHAR2(100),
POT_COLOR VARCHAR2(100),
SHAPE VARCHAR2(200),
FLOWER_NAME VARCHAR2(200)
*/
CREATE TABLE POT(
	POT_NUM NUMBER,
	POT_COLOR VARCHAR2(100),
	POT_SHAPE VARCHAR2(100),
	FLOWER_NAME VARCHAR2(100),
	CONSTRAINT POT_PK PRIMARY KEY(POT_NUM),
	CONSTRAINT FLOWER_FK FOREIGN KEY(FLOWER_NAME) REFERENCES FLOWER(FLOWER_NAME)
);


