-- 데이터 조회하기
SELECT * FROM FLOWER;

-- 데이터 추가하기
INSERT INTO FLOWER (FLOWER_NAME,FLOWER_COLOR,FLOWER_PRICE)
VALUES('장미', 'RED', 3000);

INSERT INTO FLOWER (FLOWER_NAME,FLOWER_COLOR,FLOWER_PRICE)
VALUES('해바리기', 'YELLOW', 5000);

-- 할미꽃, WHITE, 9000
INSERT INTO FLOWER (FLOWER_NAME,FLOWER_COLOR,FLOWER_PRICE)
VALUES('할미꽃', 'WHITE', 9000);

SELECT * FROM POT;

INSERT INTO POT(POT_NUM,POT_COLOR,POT_SHAPE,FLOWER_NAME)
VALUES('20230323001','WHITE', '물레방이', '장미');

INSERT INTO POT(POT_NUM,POT_COLOR,POT_SHAPE,FLOWER_NAME)
VALUES('20230323002','BLACK', '사각형', '장미');

INSERT INTO POT(POT_NUM,POT_COLOR,POT_SHAPE,FLOWER_NAME)
VALUES('20230323003','BLACK', '사각형', '할미꽃');

INSERT INTO POT(POT_NUM,POT_COLOR,POT_SHAPE,FLOWER_NAME)
VALUES('20230323004','BLUE', '타원형', '할미꽃');

-- 삭제 : 부모와 자식 중 자식 테이블에서 참조하는 값들을 먼저 삭제해야 한다.
DELETE FROM POT WHERE FLOWER_NAME = '장미';
DELETE FROM FLOWER WHERE FLOWER_NAME = '장미';

-- 수정하기 : UPDATE
UPDATE POT 
SET POT_SHAPE = '물레방아'
WHERE FLOWER_NAME = '할미꽃';

--================================================
-- 1
-- PLAYER 테이블의 모든 데이터 조회하기
SELECT * FROM PLAYER;

-- PLAYER 테이블에서 TEAM_ID가 'K01'인 선수 조회하기
SELECT * FROM PLAYER WHERE TEAM_ID = 'K01';

-- PLAYER 테이블에서 TEAM_ID가 'K01'이 아닌 선수 조회하기
SELECT * FROM PLAYER WHERE TEAM_ID != 'K01';

-- PLAYER 테이블에서 WHIGHT가 70이상이고 80이하인 선수 조회하기
SELECT * FROM PLAYER 
WHERE WEIGHT >= 70 AND WEIGHT <= 80;

SELECT * FROM PLAYER 
WHERE WEIGHT BETWEEN 70 AND 80; -- BETWEEN은 이상 이하의 경우에만 사용이 가능

-- PLAYER 테이블에서 TEAM_ID가 'K03'이고 HEIGHT가 180 보다 작은 선수 조회하기
SELECT * FROM PLAYER 
WHERE TEAM_ID = 'K03' AND HEIGHT < 180; -- 조건은 여러개 가능하다

-- PLAYER 테이블에서 HEIGHT가 170이상이고 WEIGHT가 80이상인 선수 이름 검색
SELECT PLAYER_NAME FROM PLAYER 
WHERE HEIGHT > 170 AND WEIGHT > 80;

-- PLAYER 테이블에서 TEAM_ID가 'K02' 또는 'K07'이고 포지션은 'MF'인 선수 검색
SELECT * FROM PLAYER
WHERE (TEAM_ID = 'K02' OR TEAM_ID = 'K07') AND "POSITION" = 'MF';

SELECT * FROM PLAYER
WHERE TEAM_ID IN ('K02','K07') AND "POSITION" = 'MF'; -- 간결하게표시

-- 2
-- 사원(EMPLOYEES)테이블 조회하기
SELECT * FROM EMPLOYEES;

-- 사원테이블에서 이름, 직종, 급여를 조회하세요
SELECT FIRST_NAME, JOB_ID, SALARY 
FROM EMPLOYEES;

SELECT EMPLOYEE_ID,FIRST_NAME,JOB_ID,SALARY,COMMISSION_PCT*SALARY -- 보너스비율 * 급여를통해 나타내준다
FROM EMPLOYEES;

-- 사원테이블에서 급여가 10000이상인 사원들의 사번, 이름, 급여순으로 출력
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES 
WHERE SALARY >= 10000 ;

-- 사원테이블에서 이름이 Michael인 사원의 사번, 이름을 조회
SELECT EMPLOYEE_ID, FIRST_NAME FROM EMPLOYEES 
WHERE FIRST_NAME ='Michael';

-- 사원테이블에서 급여가 10000이상이면서 13000이하인 사원의 정보를 
-- 이름, 급여 순으로 조회하세요.
SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY >= 10000 AND SALARY <= 13000;
WHERE SALARY BETWEEN 10000 AND 13000;

